.

diff --git a/myhash b/myhash
--- a/myhash
+++ b/myhash
@@ -1,9 +1,16 @@
 #!/bin/bash
 
+salt_file="/tmp/${USER}_salt"
+if [ ! -f "$salt_file" ]; then
+  echo 'Error: no salt file' 1>&2
+  exit 1
+fi
+
+
 INP="$1"
 
-which sha256sum &> /dev/null && SHA256SUM=`which sha256sum`
-which gsha256sum &> /dev/null && SHA256SUM=`which gsha256sum`
+\which sha256sum &> /dev/null && SHA256SUM=`which sha256sum`
+\which gsha256sum &> /dev/null && SHA256SUM=`which gsha256sum`
 
 HASH=$(echo "${INP}`cat /tmp/${USER}_salt`" | $SHA256SUM)
 
